apiVersion: v1
kind: Service
metadata:
  name: ip2country-service
  namespace: ip2country
spec:
  selector:
    app: ip2country
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort
