app:
  name: 'ip2country'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'ip2country'

cache:
  size: 10

repository:
  type: 'disk'

diskRepository:
  relativePath: 'internal/repositories/disk/data.json'

rateLimiter:
  type: 'local'
  maxRequests: 10
  userRequests: 5
  interval: 10s
  bucketTTL: 10s
  cleanInterval: 10s
  redisAddr: 'localhost:6379'
