app:
  name: 'ip2country'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'ip2country'

cache:
  size: 10

repository:
  type: 'disk'

diskRepository:
  relativePath: 'internal/repositories/disk_repository/data.json'

