basePath: /v1
definitions:
  v1.findCountryResponse:
    properties:
      city:
        type: string
      country:
        type: string
    type: object
  v1.response:
    properties:
      error:
        example: message
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Translating IP 2 Country
  title: IP2CountryNCity API
  version: "1.0"
paths:
  /find-country:
    get:
      consumes:
      - application/json
      description: Find country by IP
      operationId: find-country
      parameters:
      - description: IP address
        in: query
        name: ip
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.findCountryResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Find Country
swagger: "2.0"
